/**
 * Fixed types for the extension/library mode.
 * Also includes inherited types from the parent extension in library mode.
 */

import type { MODULE_NAME } from '@/module-config';

/**
 * 1. CORE TYPES
 * Core Types for system utilities and libraries.
 */
export type MessagePage = 'background' | `content/${typeof MODULE_NAME}` | 'popup' | 'options';

interface MessageErrorResponse { error: true; message: string }
interface MessageSuccessResponse<T> { error: false; data: T }

export type MessageResponse<T> = MessageErrorResponse | MessageSuccessResponse<T>;

export type MessageListener<T = any, TReturn = any> = (
    data: T,
    meta: {
        sender: chrome.runtime.MessageSender;
        ok: (data: TReturn) => MessageSuccessResponse<TReturn>;
        fail: (message: string) => MessageErrorResponse;
    },
) => MessageResponse<TReturn> | Promise<MessageResponse<TReturn>> | void | Promise<void>;

export type Message<T = any> = {
    namespace: undefined;
} | {
    namespace: string;
    targetPage: MessagePage;
    name: string;
    data?: T;
};

/**
 * Types for modules, exports and messages
 */

/**
 * 2. MODULE SPECIFIC TYPES
 * Popup script must implement this interface to be compatible in library mode.
 */
export interface PopupModule {
    urlMatches: (url: string) => boolean;

    /**
     * Used for fetching all available downloads for the active tab
     */
    getInfo: (url: string, tabId: number, tab: chrome.tabs.Tab) => Promise<MediaInfo>;

    downloadItem: (download: Download, info?: MediaInfo) => Promise<void>;

    convertToMp3?: (
        bitrate: Mp3Bitrate,
        startTime: number | null,
        endTime: number | null,
        info?: MediaInfo,
    ) => Promise<void>;

    downloadThumbnail?: (thumbnail: Thumbnail, info?: MediaInfo) => Promise<void>;

    downloadSubtitle?: (subtitle: Subtitle, info?: MediaInfo) => Promise<void>;
}

export type QualityLabel = 'sd' | 'hd' | '1080' | '2k' | '4k' | '8k';

export interface Download {
    type: 'AudioVideo' | 'AudioOnly' | 'VideoOnly';
    id: string; // Unique identifier for the download
    title?: string;
    quality: string;
    url: string;
    format: string;
    filesize?: number;
    videoQuality?: { label: QualityLabel; fps?: number };
    width?: number;
    height?: number;
}

export interface Thumbnail {
    label: string;
    url: string;
    width?: number;
    height?: number;
}

interface Subtitle {
    languageCode: string;
    languageName?: string;
    url: string;
    format: string;
    autoGenerated?: boolean;
}

export interface SingleInfo {
    type: 'single';
    id: string;
    title: string;
    length: number;
    description?: string;
    author?: string;
    downloads: Download[];
    thumbnailUrl?: string;
    thumbnails?: Thumbnail[];
    subtitles?: Subtitle[];
}

export interface ListInfo {
    type: 'list';
    downloads: Download[];
}

/**
 * Single means the downloads belong to a single video (e.g. a Dailymotion video),
 * While list means the downloads may belong to multiple videos or all available videos on the page (e.g. Facebook feed).
 */
export type MediaInfo = SingleInfo | ListInfo;

/**
 * 3. INHERITED TYPES
 * Inherited types and configuration from parent extension in library mode,
 * extend these types as needed for the module's specific functionality.
 */

export type FilenamePattern = 'filename' | 'source-website' | 'quality' | 'date' | 'time';

export type Mp3Bitrate = '128' | '192' | '256' | '320';

export interface ExtensionOptions {
    /**
     * General Settings
     */

    theme: 'light' | 'dark' | 'system';

    mp3DefaultBitrate: Mp3Bitrate;

    // Download settings
    saveAsDialogEnabled: boolean;
    downloadDirectory: string;

    // Filename settings
    filenamePattern: FilenamePattern[];
    filenameOnConflict: 'uniquify' | 'prompt' | 'overwrite';
    removeSpecialCharacters: boolean;
    replaceSpecialCharactersWith: string;

    limitFilenameCharacters: boolean;
    filenameCharacterLimit: number;
    filenameCaseManagementEnabled: boolean;
    filenameCaseManagement: 'original' | 'lowercase' | 'uppercase';
}

export interface UserData {
    installedAt: number | null;
    downloadsCount: number;
}
